/*
* Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Distribution License v. 1.0, which is available at
* http://www.eclipse.org/org/documents/edl-v10.php.
*
* SPDX-License-Identifier: BSD-3-Clause
*/

package javax.servlet.jsp.tagext;

import java.io.InputStream;

/**
 * Translation-time information on a JSP page. The information corresponds to the XML view of the JSP page.
 *
 * <p>
 * Objects of this type are generated by the JSP translator, e.g. when being pased to a TagLibraryValidator instance.
 */
abstract public class PageData {

    /**
     * Sole constructor. (For invocation by subclass constructors, typically implicit.)
     */
    public PageData() {
    }

    /**
     * Returns an input stream on the XML view of a JSP page. The stream is encoded in UTF-8. Recall tht the XML view of
     * a JSP page has the include directives expanded.
     * 
     * @return An input stream on the document.
     */
    abstract public InputStream getInputStream();
}
