///////////////////////////////////////////////////////////////////////
NOTE TO WRITERS:
This is included at the tail end of the Title page.
The following section should be customized for the technology.
This is provided to allow each technology to customize legacy acronym names
that are used in this TCK. 
Add additional lines as needed for acronyms found in your TCK user guide.
///////////////////////////////////////////////////////////////////////

References in this document to JSTL refer to the Jakarta Standard Tag Library unless otherwise noted.